#!/usr/bin/env bash
# run-this-loop.sh — engine-agnostic loop runner generated by LoopPrint.
#
# It implements the four atoms literally:
#   Goal      — you state it once (in loop-spec.yaml); this script doesn't re-derive it.
#   State     — appended to $STATE_FILE every iteration (never reset mid-run).
#   Verifier  — verify.sh, run as a separate process; exit 0 = GREEN (done), non-zero = RED. EXTERNAL by construction.
#   Stop      — whichever hits first: GREEN, $MAX_ITERS, the budget, or the HALT file.
#
# Fill the four variables below (the wizard does this from loop-spec.yaml), implement make_change(),
# and run:  bash run-this-loop.sh
set -euo pipefail

# ---- the four atoms (filled by LoopPrint from loop-spec.yaml) ----------------
GOAL="<one-sentence goal>"
STATE_FILE="${STATE_FILE:-state.md}"
VERIFIER="${VERIFIER:-verify.sh}"    # external gate: a script that exits 0 = GREEN. Runs as its own process —
                                     # this runner never eval's a command string from the spec (see SECURITY.md).
MAX_ITERS="${MAX_ITERS:-10}"
HALT_FILE="${HALT_FILE:-HALT}"
AUTONOMY="${AUTONOMY:-checkpoint}"   # full | checkpoint | dry-run

log() { printf '%s  %s\n' "$(date -u +%FT%TZ)" "$*" | tee -a "$STATE_FILE" >&2; }
run_verifier() { bash "$VERIFIER"; }   # the only thing that can declare success

# ---- the maker step: produce one change toward the goal ----------------------
# Replace this with the actual work. Keep it the MAKER only — never let it grade itself.
# Examples (pick one, delete the rest):
#   oh-my-claudecode:  claude -p "Make one change toward: $GOAL. Then stop."
#   sub-agent dispatch: your-dispatch --role executor --task "$GOAL"        # checker runs separately, below
#   plain CLI:         your_tool --fix
make_change() {
  echo "TODO: implement the maker step (one change toward: $GOAL)" >&2
  return 0
}

# ---- the loop ----------------------------------------------------------------
iter=0
log "START goal=\"$GOAL\" max_iters=$MAX_ITERS autonomy=$AUTONOMY"

# checkpoint autonomy needs an interactive terminal; refuse rather than hang/exit silently in CI.
if [ "$AUTONOMY" = "checkpoint" ] && [ ! -t 0 ]; then
  log "ERROR: autonomy=checkpoint needs a TTY, but stdin is not interactive (e.g. CI). Set AUTONOMY=full to run unattended."
  exit 5
fi

# Verify-first: if the goal is already met, do nothing.
if run_verifier; then log "GREEN at iter 0 — nothing to do."; exit 0; fi

while :; do
  [ -f "$HALT_FILE" ] && { log "HALT file present — stopping."; exit 3; }
  iter=$((iter + 1))
  if [ "$iter" -gt "$MAX_ITERS" ]; then log "STOP: hit max_iterations ($MAX_ITERS) without GREEN."; exit 2; fi

  log "--- iteration $iter ---"

  if [ "$AUTONOMY" = "checkpoint" ]; then
    read -r -p "Proceed with iteration $iter? [y/N] " ok || ok=n
    [ "$ok" = "y" ] || { log "User declined at checkpoint."; exit 4; }
  fi
  if [ "$AUTONOMY" = "dry-run" ]; then log "DRY-RUN: would make a change; skipping."; exit 0; fi

  make_change || log "maker step returned non-zero (continuing to verify)."

  # External verifier — the ONLY thing that can declare success. Maker != checker.
  if run_verifier; then
    log "GREEN at iter $iter — goal met. DONE."
    exit 0
  else
    log "RED at iter $iter — verifier rejected; iterating."
  fi
done
